### PR TITLE
more ocropy wrapper fixes

### PR DESCRIPTION
**Pull request by bertsky**
@wrznr you might need this, too.

### CODE REVIEW

**Comment by wrznr** [comment]
Is there a schedule for bundling this as an improved `ocrolib`?

**Comment by bertsky** [comment]
> Is there a schedule for bundling this as an improved `ocrolib`?

I'll be on holiday the next 2w, so let's say early August. (But the first step is [restructuring OCR-D/ocropy](https://github.com/cisocrgroup/cis-ocrd-py/pull/10#issuecomment-511792849). If anyone wants to help with that in the meantime, they are welcome.)

**Comment by bertsky** [comment]
Wait, there's one more: page-level deskewing. (Yes I know, we are still waiting for the PAGE-XML update in core to give us `PageType.orientation`. But at least we can already create `AlternativeImage`...)

**Comment by bertsky** [comment]
@finkf done, you can merge now (sorry about the noise).

**Comment by bertsky** [comment]
sorry again – this just popped up!

**Pull request merged**
