### PR TITLE
separate preprocessing steps and use AlternativeImage in ocropy wrappers

### PR DESCRIPTION
**Pull request by bertsky**
details see changelog, roughly:

- extra processors for binarization, deskewing, dewarping with ocropy
- pipeline relies on `AlternativeImage` – as reference implementation showing how to deal with relative coordinates and coordinate transforms (rotation, translation, offset)
- use variant of ocropy page segmentation to re-segment region rectangles into line masks
- extra module for common ocropy functions 

I will provide more examples and images shortly.

### CODE REVIEW

**Comment by bertsky** [comment]
The last commit maintains that functions in `common` are the same as those in OCR-D/ocrd_tesserocr#48.

**Comment by bertsky** [comment]
examples:

from `euler_rechenkunst01_1738` page `phys0006` region `r_5_3` (as annotated by `OCR-D-GT-SEG-LINE`): 

* the cropped raw region
OCR-D-IMG_0006_r_5_3
* and some cropped raw lines:
OCR-D-IMG_0006_r_5_3_tl_10
OCR-D-IMG_0006_r_5_3_tl_11
OCR-D-IMG_0006_r_5_3_tl_12
OCR-D-IMG_0006_r_5_3_tl_13
* now the binarized and deskewed region:
OCR-D-IMG-BIN_0006_r_5_3
* and the line images masked by their rotated polygons:

**Comment by bertsky** [comment]
Please do not merge yet. I will push more changes soon that will further improve:
- rebase `common` functions on processing polygon coordinates throughout (instead of just bounding boxes)
- better ensapsulation
- _resegmentation_ as a separate processor (not mixed into `common`), and also used to clip graphic/separator foreground components out of text regions (where they overlap in the annotation)
- more improvements on ocropy line segmentation

**Comment by bertsky** [comment]
Besides the changes already announced, this last commit includes a new processor **clip** which can suppress neighbouring segments (lines vs. line, or regions vs. region – including `SeparatorRegion`, `GraphicRegion` etc) by clipping connected components belonging to them to white in the segment's `AlternativeImage`. (I had to use image clipping instead of polygon shrinking here, because many frequent cases would create interior islands or non-contiguous polygons.) 

Due to the nature of comparison between neighbours though, the segments must not have `@orientation` or `AlternativeImage` already. That is, for region-level clipping, any region-level binarization or deskewing must come _afterwards_. 

Line-level clipping can be seen as an alternative to resegmentation which does not depend on Ocropy segmentation.

**Comment by bertsky** [comment]
Here are some examples. Starting with the above `euler_rechenkunst01_1738` page `phys0006` region `r_5_3` again:

* clipping the region results in a raw image with white spots where neighbours (here `r_5_2` and `r_5_4`) intrude:
OCR-D-IMG-CLIP_0006_r_5_3

* this gives an improved starting point for resegmentation:
phys_0006_r_5_3_region_labels

* these are the original polygon line masks annotated in the GT:
phys_0006_r_5_3_tl_10_line_mask
phys_0006_r_5_3_tl_11_line_mask
phys_0006_r_5_3_tl_12_line_mask
phys_0006_r_5_3_tl_13_line_mask
phys_0006_r_5_3_tl_14_line_mask

* now we have a parameter in resegmentation that allows extending them by some amount of pixels first  (to compensate for too tight cropping):
phys_0006_r_5_3_tl_10_line_mask_extended
phys_0006_r_5_3_tl_11_line_mask_extended
phys_0006_r_5_3_tl_12_line_mask_extended
phys_0006_r_5_3_tl_13_line_mask_extended
phys_0006_r_5_3_tl_14_line_mask_extended

* this is how the intersection with the region labels looks like:
phys_0006_r_5_3_tl_10_line_labels
phys_0006_r_5_3_tl_11_line_labels
phys_0006_r_5_3_tl_12_line_labels
phys_0006_r_5_3_tl_13_line_labels
phys_0006_r_5_3_tl_14_line_labels

* and thus, the mask of the largest label, respectively:
phys_0006_r_5_3_tl_10_line_mask_largest
phys_0006_r_5_3_tl_11_line_mask_largest
phys_0006_r_5_3_tl_12_line_mask_largest
phys_0006_r_5_3_tl_13_line_mask_largest
phys_0006_r_5_3_tl_14_line_mask_largest

* finally, the recropped and dewarped images again:
OCR-D-IMG-DEWARP_0006_r_5_3_tl_10
OCR-D-IMG-DEWARP_0006_r_5_3_tl_11
OCR-D-IMG-DEWARP_0006_r_5_3_tl_12
OCR-D-IMG-DEWARP_0006_r_5_3_tl_13
OCR-D-IMG-DEWARP_0006_r_5_3_tl_14

**Comment by bertsky** [comment]
Here are some more clipping examples from `euler_rechenkunst01_1738`:

* page `phys0003` region `TextRegion_1479743994178_731`:
OCR-D-IMG-CLIP_0003_TextRegion_1479743994178_731

* page `phys0004` region `r_6_2` (not perfect due to suboptimal binarization):
OCR-D-IMG-CLIP_0004_r_6_2


* page `phys0004` region `r_9_3`:
OCR-D-IMG-CLIP_0004_r_9_3

* page `phys0004` region `r_9_4`:
OCR-D-IMG-CLIP_0004_r_9_4

* page `phys0005` region `r_8_5`:
OCR-D-IMG-CLIP_0005_r_8_5

* page `phys0005` region `TextRegion_1475759982805_45`:
OCR-D-IMG-CLIP_0005_TextRegion_1475759982805_45

* page `phys0005` region `TextRegion_1475759982805_44`:
OCR-D-IMG-CLIP_0005_TextRegion_1475759982805_44

* page `phys0006` region `r_5_2` (just above the first example):
OCR-D-IMG-CLIP_0006_r_5_2

* page `phys0006` region `r_5_4` (just below the first example):
OCR-D-IMG-CLIP_0006_r_5_4

**Comment by wrznr** [comment]
@finkf Please review and/or merge!

**Comment by finkf** [comment]
I am OK to merge this.  But wouldn't it make more sense to separate all the `ocropus` related parts of `ocrd-cis` in its own `ocrd` module?

**Comment by bertsky** [comment]
Splendid! Definitely, it does make sense to have a separate module with all Ocropy based processors. That's exactly what we are planning to do. This is just the first step, so others can start experimenting already. Remember, I started this in your repo because of all your good work on the recognition processor. 

The idea is to restructure the repo OCR-D/ocropy into 2 packages, **ocrolib** (current `ocrolib` modules plus non-trivial functions in current CLIs) and **ocropus** (CLIs only, and packaged properly, possibly ported to `click`). (Both names are still free in PyPI!) This fork is meant to live on as an improved, Python 3 ported, better encapsulated incarnation, which can probably be PRed back  into tmbdev/ocropy.

Moreover, OCR-D/ocrd_ocropy can then become a simple OCR-D wrapper based on `ocrolib`.

Based on this, I will re-commit all changes not strictly related to wrappers I made here to the new ocrolib. Finally, I will introduce the new processors into OCR-D/ocrd_ocropy, and also rewrite the segmentation processor (the only one I have not touched yet).

**Comment by finkf** [comment]
OK. Ill merge then.

**Comment by bertsky** [comment]
thx!

**Pull request merged**
